zoo = 'python', 'snake', 'dog' #I usually can use ()
print('Number of animal -', len(zoo))
new_zoo = ('monkey', 'bird')
print('Number of animal in new zoo -', len(new_zoo))
print('Number of all animals -', len(zoo) + len(new_zoo))
print(zoo[0],':))')
